ALTER TABLE users
ADD COLUMN IF NOT EXISTS username VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS first_name VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS last_name VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS phone VARCHAR(255) NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMP NULL DEFAULT NULL,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL DEFAULT NULL;