// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	http2 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/auth/adapter/in/http"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/auth/adapter/out"
	security2 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/auth/adapter/out/security"
	service2 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/auth/application/service"
	http3 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/cart/adapter/in/http"
	persistence2 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/cart/adapter/out/persistence"
	service3 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/cart/application/service"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/shared/event"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/shared/validator"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/adapter/in/http"
	out2 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/adapter/out"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/adapter/out/persistence"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/adapter/out/security"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/application/service"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/authorization/casbin"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/config"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/database"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/logger"
)

// Injectors from wire.go:

func InitializeServer(eventPublisher event.Publisher) (*Server, error) {
	loggerLogger := logger.NewLogger()
	postgresConfig := config.LoadPostgresConfig()
	db, err := database.NewGormDB(postgresConfig)
	if err != nil {
		return nil, err
	}
	enforcer, err := casbin.ProvideEnforcer(db)
	if err != nil {
		return nil, err
	}
	authorizer := casbin.ProvideAuthorizer(enforcer)
	userRepository := persistence.NewGormUserRepository(db)
	passwordHasher := security.NewBcryptHasher()
	userService := service.NewUserService(userRepository, passwordHasher, loggerLogger)
	validate := validator.NewValidator()
	handler := http.NewHandler(userService, validate)
	userAuthenticator := out.NewUserAuthenticatorImpl(userService)
	jwtConfig := config.NewJWTConfig()
	jwtGenerator := security2.NewJWTGenerator(jwtConfig)
	authUsecase := service2.NewAuthService(userAuthenticator, jwtGenerator, loggerLogger)
	httpHandler := http2.NewHandler(authUsecase, validate)
	cartRepository := persistence2.NewGormCartRepository(db)
	userReaderImpl := out2.NewUserReaderImpl(userRepository)
	manager := database.NewGormTxManager(db)
	cartUsecase := service3.NewCartService(cartRepository, userReaderImpl, manager, eventPublisher)
	handler2 := http3.NewHandler(cartUsecase)
	jwtVerifier := security2.NewJWTVerifier(jwtConfig)
	server := NewServer(loggerLogger, authorizer, handler, httpHandler, handler2, jwtVerifier)
	return server, nil
}
