// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/adapter/in/http"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/adapter/out/persistence"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/application/service"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/config"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/database"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/logger"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	mySQLConfig := config.LoadMySQLConfig()
	db, err := database.NewGormDB(mySQLConfig)
	if err != nil {
		return nil, err
	}
	userRepository := persistence.NewGormUserRepository(db)
	loggerLogger := logger.NewLogger()
	userUsecase := service.NewUserService(userRepository, loggerLogger)
	handler := http.NewHandler(userUsecase)
	server := NewServer(handler)
	return server, nil
}
