// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	http2 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/task/adapter/in/http"
	persistence2 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/task/adapter/out/persistence"
	service2 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/task/application/service"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/adapter/in/http"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/adapter/out/persistence"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/application/service"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/config"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/database"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/logger"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	mySQLConfig := config.LoadMySQLConfig()
	db, err := database.NewGormDB(mySQLConfig)
	if err != nil {
		return nil, err
	}
	userRepository := persistence.NewGormUserRepository(db)
	loggerLogger := logger.NewLogger()
	userService := service.NewUserService(userRepository, loggerLogger)
	handler := http.NewHandler(userService)
	taskRepository := persistence2.NewGormTaskRepository(db)
	manager := database.NewGormTxManager(db)
	taskUsecase := service2.NewTaskService(taskRepository, userService, manager)
	httpHandler := http2.NewHandler(taskUsecase)
	server := NewServer(handler, httpHandler)
	return server, nil
}
