// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	http3 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/cart/adapter/in/http"
	persistence3 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/cart/adapter/out/persistence"
	service3 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/cart/application/service"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/shared/event"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/shared/validator"
	http2 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/task/adapter/in/http"
	persistence2 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/task/adapter/out/persistence"
	service2 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/task/application/service"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/adapter/in/http"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/adapter/out"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/adapter/out/persistence"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/adapter/out/security"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/internal/user/application/service"
	casbin2 "github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/authz/casbin"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/config"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/config/casbin"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/database"
	"github.com/ryvasa/go-ddd-hexagonal-modular-monolith/pkg/logger"
)

// Injectors from wire.go:

func InitializeServer(eventPublisher event.Publisher) (*Server, error) {
	loggerLogger := logger.NewLogger()
	enforcer, err := casbin.ProvideCasbinEnforcer()
	if err != nil {
		return nil, err
	}
	casbinEnforcer := casbin2.ProvideAuthorizer(enforcer)
	postgresConfig := config.LoadPostgresConfig()
	db, err := database.NewGormDB(postgresConfig)
	if err != nil {
		return nil, err
	}
	userRepository := persistence.NewGormUserRepository(db)
	passwordHasher := security.NewBcryptHasher()
	jwtConfig := config.NewJWTConfig()
	jwtGenerator := security.NewJWTGenerator(jwtConfig)
	userService := service.NewUserService(userRepository, passwordHasher, jwtGenerator, loggerLogger)
	validate := validator.NewValidator()
	handler := http.NewHandler(userService, validate)
	taskRepository := persistence2.NewGormTaskRepository(db)
	manager := database.NewGormTxManager(db)
	taskUsecase := service2.NewTaskService(taskRepository, userService, manager, eventPublisher)
	httpHandler := http2.NewHandler(taskUsecase)
	cartRepository := persistence3.NewGormCartRepository(db)
	userReaderImpl := out.NewUserReaderImpl(userRepository)
	cartUsecase := service3.NewCartService(cartRepository, userReaderImpl, manager, eventPublisher)
	handler2 := http3.NewHandler(cartUsecase)
	jwtVerifier := security.NewJWTVerifier(jwtConfig)
	server := NewServer(loggerLogger, casbinEnforcer, handler, httpHandler, handler2, jwtVerifier)
	return server, nil
}
